### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by anonym24** [youtube/yt-android-player#21]

**Comment by anonym24** [comment]
I'm also facing next errors in my Google Console: https://stackoverflow.com/questions/45172972/getting-nullpointerexception-at-onfiltertoucheventforsecurity

**Comment by anonym24** [comment]
solved. it was issue with optional parameters in this `fun`

**Comment by jupitorapps** [comment]
@anonym24

This issue is in my app also. can you please explain in which function and which parameter issue was there so that I can also check and solve it.
